import Sidebar from './components/Sidebar';
import { Roboto } from 'next/font/google';
import './globals.css';
import { Metadata } from 'next';
import { PersonalContextProvider } from './contexts/personalContex';
import { SettingsContextProvider } from './contexts/settingsContext';

export const metadata: Metadata = {
  title: 'Pactto',
  description: 'Generated by Next.js',
};

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <PersonalContextProvider>
        <SettingsContextProvider>
          <body className={roboto.className}>
            <Sidebar />
            {children}
          </body>
        </SettingsContextProvider>
      </PersonalContextProvider>
    </html>
  );
}
